/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109192-gc8e9cc8d20-20221124"
#endif /* AVUTIL_FFVERSION_H */
